name: refills
description: "A new Flutter project."
publish_to: "none"
version: 1.3.0+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
